### ISSUE TITLE
Ruben Cedeno - Issue with tail array

### ISSUE THREAD

**Issue by anonyymous1** [anonyymous1/Battle_Snakes#2]
Cant seem to find out why the tail is not adding to the array.
When I console.log, the array appears.

![Screen Shot 2020-11-06 at 9 20 21 AM](https://user-images.githubusercontent.com/71801837/98376356-5c4cc500-2011-11eb-9001-2f05cc72e248.png)

**Comment by romebell** [comment]
Issue solved ✅

Next item: 
- [ ] Get snake position working according to `movement`
